import { TopBar } from '../components/TopBar';
import { Cabin } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { CssBaseline, ThemeProvider } from '@mui/material';
import theme from './theme';
import './global.css';

import type { Metadata } from 'next';

const cabinFont = Cabin({
    variable: '--font-cabin',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Tab Samurai',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={cabinFont.className}>
                <InitColorSchemeScript attribute='class' />
                <AppRouterCacheProvider>
                    <ThemeProvider theme={theme}>
                        <CssBaseline />

                        <TopBar />

                        {children}
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
